### ISSUE TITLE
Store all time information in UTC

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#61] opened 2020-07-05 07:00 UTC
From @strogonoff :

> this looks like a ticket for the desktop software which should apply current user’s local timezone adjustment when storing timestamps in Zulu/UTC (I think it currently doesn’t)

_Originally posted by @strogonoff in https://github.com/geolexica/isotc211-glossary/pull/17#issuecomment-653501395_

**Comment by ronaldtse** [comment] 2020-07-05 07:01
@phuonghuynh can you help here? Thanks!

**Comment by strogonoff** [comment] 2020-07-05 10:04
Duplicate of https://github.com/glossarist/glossarist-desktop/issues/50

**Closed by strogonoff** 2020-07-05 10:04 UTC
Labels: bug
