### ISSUE TITLE
Card view: Math not rendering

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#101] opened 2020-08-19 17:08 UTC
Concept 86 in MLGT:

<img width="1312" alt="image" src="https://user-images.githubusercontent.com/11865/90667793-9f549300-e281-11ea-9e42-1fe05210c3cd.png">

**Comment by strogonoff** [comment] 2020-08-20 05:04
@ronaldtse is this a dupe of https://github.com/glossarist/glossarist-desktop/issues/38?

**Comment by ronaldtse** [comment] 2020-08-20 05:37
It's a deterioration from #38 -- in #38 only when the definition is displayed in the sidebar math doesn't show. The Card view worked back then. Now the Card view doesn't show.

**Comment by strogonoff** [comment] 2020-08-25 06:02
I we have single logic of displaying math that assumes $$ identifiers. Since we have switched to another way of entering math [because](https://github.com/glossarist/glossarist-desktop/issues/38#issuecomment-653320173)

> The reason is the translator's ability to preview with MathJax from the Excel sheet.

I think it should have broke everywhere after that, and will be fixed in one go.

**Comment by strogonoff** [comment] 2020-08-25 06:11
This should be fixed now. Unfortunately, math can be overflowing (card) and/or clipping (side panel). I’m not sure if this is caused by [the updated math format](https://github.com/glossarist/glossarist-desktop/issues/38#issuecomment-653320173).

<img width="1312" alt="Screenshot 2020-08-25 at 3 08 34 PM" src="https://user-images.githubusercontent.com/292959/91129421-8ab93600-e699-11ea-9984-a2a22b6ec345.png">

**Comment by ronaldtse** [comment] 2020-08-25 06:31
Thanks @strogonoff , the math overflowing here is normal because, the formula is really that long. I'm not sure if we can enforce line breaks within an equation because it could affect semantics.

**Comment by strogonoff** [comment] 2020-08-25 06:32
OK. I am closing this, since math is rendering.

For now, long math lines make card and panel contents scroll. It is an open question whether long lines of math can be broken up in a way that does not interfere with their meaning. (I suppose not per Ronald’s comment.) We may file another issue if we will want to deal with long lines better.

**Closed by strogonoff** 2020-08-25 06:32 UTC
Labels: bug, 🧮 math
