### ISSUE TITLE
Glossarist "crashes" at normal quitting in macOS Catalina

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#103] opened 2020-08-21 02:17 UTC
In 1.6.17, whenever I quit Glossarist Desktop normally, it soon shows this message:
<img width="545" alt="Screen Shot 2020-08-21 at 10 16 52 AM" src="https://user-images.githubusercontent.com/11865/90844879-8211e880-e397-11ea-8872-7a0f174f389c.png">

This behavior did not show in 1.6.x I used earlier.

**Comment by strogonoff** [comment] 2020-08-21 02:24
Could you attach log files here? Should be here:

%USERPROFILE%\AppData\Roaming\Glossarist\logs

**Comment by ronaldtse** [comment] 2020-08-21 03:03
I'm on macOS, USERPROFILE is for Windows?

**Comment by strogonoff** [comment] 2020-08-21 03:19
Sorry, misread your message on the phone. (Was surprised to think you’re on Windows)

On macOS: `~/Library/Logs/Glossarist/{process type}.log`

**Comment by strogonoff** [comment] 2020-08-21 06:27
(Since it’s not reproducible on my machine, I’ll wait for logs)

**Comment by strogonoff** [comment] 2020-08-30 21:45
The issue was likely with worker thread for Git management. It was not explicitly shut down and thus force terminated at app quit. Addressed in Coulomb, confirmed no crash report dialog at quit anymore on macOS Catalina.

**Closed by strogonoff** 2020-08-30 21:45 UTC
Labels: bug
