### ISSUE TITLE
Issue with empty register

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-desktop#152] opened 2020-11-26 07:18 UTC
From @rob-metalinkage

In this repo:
> https://github.com/rob-metalinkage/glossarist_test
> if i use either my password or PAT it just stays offline
> if i use something else it asks for the password again.

@strogonoff could you help have a look? This repository is already created from the Glossarist template repo according to this: https://www.glossarist.org/docs/adopt/2-infrastructure/

I believe the YAML files are also properly set.

Thanks!

**Comment by strogonoff** [comment] 2020-11-27 06:15
@ronaldtse  To troubleshoot further, please let me know the OS this happens on and the version of Glossarist Desktop.

I forked the repository and was able to connect Glossarist to my fork. I specified my GitHub password (did not try PAT). Latest GD release (1.6.40) went through QA under Windows and Ubuntu Linux, so I am reasonably sure it should work the same way on those systems.

**Comment by strogonoff** [comment] 2020-11-27 06:17
Additionally, a screenshot of the offline window would be helpful.

**Comment by rob-metalinkage** [comment] 2020-11-27 07:31
Windows 10, downloaded 2 days ago.

Nothing really  to screenshot except the Offline status window.
Show quoted text

---------- Forwarded message ---------
From: Rob Atkinson <rob@metalinkage.com.au>
Date: Fri, 27 Nov 2020, 18:16
Subject: Re: [glossarist/glossarist-desktop] Issue with empty register (#152)
To: glossarist/glossarist-desktop <reply+ACCHOYMYJZGFQCFXGP2RGR55ZR5PTEVBNHHCZSFRXI@reply.github.com>
Cc: glossarist/glossarist-desktop <glossarist-desktop@noreply.github.com>, Rob Atkinson <rob@metalinkage.com.au>, Mention <mention@noreply.github.com>


Windows 10, downloaded 2 days ago.

Nothing really  to screenshot except the Offline status window.

**Comment by strogonoff** [comment] 2020-11-27 09:22
OK—if the offline screen contains the settings button on top right, please open settings and confirm that: (1) repo URL is in https format, (2) repo URL doesn’t have trailing slash or .git suffix, (3) username specified matches your GitHub username, (4) author name and email are not empty.

If there is no settings button, try removing app configuration directory (on Windows, `C:\Users\ (username)\AppData\Roaming\Glossarist Desktop`) while the app is not running, and supplying those settings as specified above at next startup.

**Comment by rob-metalinkage** [comment] 2020-11-30 22:05
OK - seems to connect after shutting it down completely and restarting - with no other changes to anything.

**Comment by strogonoff** [comment] 2021-01-09 00:15
Closing for now since I can’t reproduce it so far.

**Closed** 2021-01-09 00:15 UTC
Labels: question
