### ISSUE TITLE
Add "Close" or "Apply" button to "Settings" dialog

### ISSUE THREAD

**Issue by ReesePlews** [glossarist/glossarist-desktop#84] opened 2020-07-09 08:29 UTC
it is not clear when modifying the "Settings" dialog on how the updated parameters are saved to the program. there is no "Close" or "Apply" button to signal to the user that updates to the input have been made. it may also be necessary that a "Cancel" button is also needed.

![__tmp_image_upload__](https://user-images.githubusercontent.com/35089343/87016814-27b73100-c20a-11ea-9203-f928470601eb.png)

**Comment by strogonoff** [comment] 2020-07-11 08:27
The currently intended behavior is for “Save all and close” button to appear iff any of the values is edited. If that doesn’t happen, please file a bug!

Note that changing repository URL after the data had been fetched for the first time can currently have unintended consequences—this should be addressed in upcoming versions.

**Closed by strogonoff** 2020-07-11 08:27 UTC
Labels: enhancement
